### PR TITLE
Enhance Docker Compose Configuration with GPU Handling

### PR DESCRIPTION
**Pull request by naufalprtm**
This pull request updates the Docker Compose configuration for the ollama service to include GPU support. The configuration includes guidelines for users on how to manage GPU detection effectively.

### **Key Changes:**

Integrated GPU support for the ollama service, enabling the utilization of available GPUs during operation.
Added detailed notes on handling GPU detection for both NVIDIA and AMD GPUs, with links to relevant installation guides.

### **Additional Notes:**

**_Users must ensure their environment is properly configured for GPU support if applicable.
If there is no GPU available, users are instructed to remove the GPU reservation section from the Docker Compose file.
This update aims to enhance the functionality of the SixGPT miner deployment while providing clear instructions for effective GPU utilization._**

### CODE REVIEW

**Comment by Mr-A96** [comment]
Okay

**Review by Mr-A96 — APPROVED** [review]

**Comment by shellzbt** [comment]
Can you modify this script so that users do not have to comment out any code for running on either CPU or GPU?

**Comment by naufalprtm** [comment]
> Can you modify this script so that users do not have to comment out any code for running on either CPU or GPU?

I have created "run_sixgpt.sh" there it will be easier for users but still need improvements to the script

**Comment by shellzbt** [comment]
> > Can you modify this script so that users do not have to comment out any code for running on either CPU or GPU?
> 
> I have created "run_sixgpt.sh" there it will be easier for users but still need improvements to the script

awesome thanks. can you add a brief description what the script does + what those potential improvements entail? then ready to merge.

**Comment by naufalprtm** [comment]
> > > Can you modify this script so that users do not have to comment out any code for running on either CPU or GPU?
> > 
> > 
> > I have created "run_sixgpt.sh" there it will be easier for users but still need improvements to the script
> 
> awesome thanks. can you add a brief description what the script does + what those potential improvements entail? then ready to merge.


# Description:
This script offers a streamlined setup process for configuring and managing Docker containers on a machine. Users are guided to select a language, verify and initialize essential configurations (such as **VANA_PRIVATE_KEY**, **VANA_NETWORK**, and **OLLAMA_API_URL**), check hardware specifications (CPU, GPU, and RAM), and interactively manage Docker resources. The script also includes prompts to install Docker and Docker Compose if they are missing, supports GPU/CPU configurations, and manages .env configurations automatically. Additionally, it facilitates easy updates and provides options to enable or disable GPU support dynamically within the Docker Compose environment.

# Suggested Improvements:
- Enhanced Error Handling:
Integrate more specific error messages for GPU/CPU detection and Docker installation failures.
- Localization Support: 
Complete language selection by providing all prompts and responses in multiple languages based on the initial user choice.
- Dynamic Network Configuration: 
Consider allowing custom Docker networks to be created based on user input for more flexible container deployments.
- Improved .env Management: 
Add checks to prevent overwriting existing variables in the .env file or ask the user to confirm before making any changes.
- Automated Container Health Checks: 
Introduce regular health checks for running containers to restart them if they become unresponsive.
These improvements would make the script more robust, user-friendly, and adaptable for a wider range of deployments.

Screenshot 2024-10-30 140202

**Pull request merged**
